#pragma checksum "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "97cc689e12c3c59a7ba2b64712d8682ea6a61bc7"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Statistic_Index), @"mvc.1.0.view", @"/Views/Statistic/Index.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\_ViewImports.cshtml"
using SM;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\_ViewImports.cshtml"
using SM.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"97cc689e12c3c59a7ba2b64712d8682ea6a61bc7", @"/Views/Statistic/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"dcc4f2dfcced338833d9bab50aca4eef0a8dd2f9", @"/Views/_ViewImports.cshtml")]
    public class Views_Statistic_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<IEnumerable<SM.Models.Statistic>>
    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml"
  
    ViewData["Title"] = "Student statistics";

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n<div class=\"border p-3\">\r\n    <div class=\"container p-3\">\r\n        <div class=\"row pt-4\">\r\n            <div class=\"col-6\">\r\n                <h2 class=\"text-primary\">Student statistics</h2>\r\n            </div>\r\n        </div>\r\n\r\n        <br /><br />\r\n\r\n");
#nullable restore
#line 16 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml"
         if (Model.Count() > 0)
        {

#line default
#line hidden
#nullable disable
            WriteLiteral(@"            <table class=""table table-bordered table-striped"" style=""width:100%"">
                <thead>
                    <tr>
                        <th>
                            Student name
                        </th>
                        <th>
                            Average
                        </th>
                        <th>
                            Unsatisfactory grades
                        </th>
                        <th>
                            Best grade
                        </th>
                    </tr>
                </thead>
                <tbody>
");
#nullable restore
#line 36 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml"
                     foreach (var statistic in Model)
                    {

#line default
#line hidden
#nullable disable
            WriteLiteral("                        <tr>\r\n                            <td width=\"40%\">");
#nullable restore
#line 39 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml"
                                       Write(statistic.Name);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                            <td width=\"10%\">");
#nullable restore
#line 40 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml"
                                       Write(statistic.Average);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                            <td width=\"30%\">");
#nullable restore
#line 41 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml"
                                       Write(statistic.NumberOfUnsatisfactoryGrades);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                            <td width=\"20%\">");
#nullable restore
#line 42 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml"
                                       Write(statistic.BestGrade);

#line default
#line hidden
#nullable disable
            WriteLiteral("</td>\r\n                        </tr>\r\n");
#nullable restore
#line 44 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml"
                    }

#line default
#line hidden
#nullable disable
            WriteLiteral("                </tbody>\r\n            </table> ");
#nullable restore
#line 46 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml"
                     }
        else
        {

#line default
#line hidden
#nullable disable
            WriteLiteral("            <h2 class=\"text-danger\">No statistic found</h2>");
#nullable restore
#line 49 "C:\Users\z003y\OneDrive\Dokumentumok\Projects\SM\SM\Views\Statistic\Index.cshtml"
                                                           }

#line default
#line hidden
#nullable disable
            WriteLiteral("\r\n    </div>\r\n</div>\r\n");
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; }
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<IEnumerable<SM.Models.Statistic>> Html { get; private set; }
    }
}
#pragma warning restore 1591
